// Re-export all constants from shared package
export {
  APP_NAME,
  CONFIG_DIR,
  CONFIG_FILE,
  DB_FILE,
  TRASH_DIR,
  DEFAULT_GITIGNORE,
  SYNC_PORT,
  SYNC_CONFLICTS_DIR,
  SYNC_SERVICE_NAME,
  SYNC_PAIRING_TTL,
  BLE_SERVICE_UUID,
  BLE_DEVICE_INFO_UUID,
  BLE_SYNC_CONTROL_UUID,
  BLE_SYNC_DATA_UUID,
  BLE_DEFAULT_MTU,
  BLE_PREFERRED_MTU,
  BLE_COMPRESS_THRESHOLD
} from '@ai-note/shared-types'
